#!/bin/bash
: ${AUTH_KUBE_KEYSTONE_PROJECT:="service"}
: ${AUTH_KUBE_KEYSTONE_PROJECT_DOMAIN:="default"}
: ${AUTH_KUBE_KEYSTONE_PROJECT_USER_ROLE:="admin"}
: ${AUTH_KUBE_KEYSTONE_DOMAIN:="default"}
: ${AUTH_KUBE_KEYSTONE_REGION:="RegionOne"}
