# Additional secrets required by this namespace:
# designate-ssl-secret - from marina service manager
# designate-user-ssl-secret - from marina service manager
# designate-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: designate-kubecfg
  namespace: os-designate
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-user-ipa
  namespace: os-designate
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-host-ipa
  namespace: os-designate
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-db-root
  namespace: os-designate
type: Opaque
data:
  mariadb-root-password: {{ AUTH_DESIGNATE_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-db
  namespace: os-designate
type: Opaque
data:
  mariadb-test-database: {{ AUTH_DESIGNATE_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_DESIGNATE_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_DESIGNATE_MARIADB_PASSWORD }}
  designate-db-name: {{ AUTH_DESIGNATE_DB_NAME }}
  designate-db-user: {{ AUTH_DESIGNATE_DB_USER }}
  designate-db-password: {{ AUTH_DESIGNATE_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-db-pool
  namespace: os-designate
type: Opaque
data:
  mariadb-test-database: {{ AUTH_DESIGNATE_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_DESIGNATE_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_DESIGNATE_MARIADB_PASSWORD }}
  designate-pool-db-name: {{ AUTH_DESIGNATE_POOL_DB_NAME }}
  designate-pool-db-user: {{ AUTH_DESIGNATE_POOL_DB_USER }}
  designate-pool-db-password: {{ AUTH_DESIGNATE_POOL_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-db-pdns
  namespace: os-designate
type: Opaque
data:
  mariadb-test-database: {{ AUTH_DESIGNATE_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_DESIGNATE_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_DESIGNATE_MARIADB_PASSWORD }}
  designate-pdns-db-name: {{ AUTH_DESIGNATE_PDNS_DB_NAME }}
  designate-pdns-db-user: {{ AUTH_DESIGNATE_PDNS_DB_USER }}
  designate-pdns-db-password: {{ AUTH_DESIGNATE_PDNS_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: designate-keystone
  namespace: os-designate
type: Opaque
data:
  designate-keystone-user: {{ AUTH_DESIGNATE_KEYSTONE_USER }}
  designate-keystone-password: {{ AUTH_DESIGNATE_KEYSTONE_PASSWORD }}
