apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-db
  name: designate-db
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3315
    protocol: TCP
    targetPort: 3315
  selector:
    openstack-app: designate-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-db-pdns
  name: designate-db-pdns
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3316
    protocol: TCP
    targetPort: 3316
  selector:
    openstack-app: designate-db-pdns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate
  name: designate
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    openstack-app: designate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-dns
  name: designate-dns
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 553
    protocol: TCP
    targetPort: 553
    name: dns-tcp
  - port: 553
    protocol: UDP
    targetPort: 553
    name: dns-udp
  selector:
    openstack-app: designate-dns
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-mdns
  name: designate-mdns
  namespace: os-designate
spec:
  clusterIP: 'None'
  sessionAffinity: 'ClientIP'
  ports:
  - port: 5354
    targetPort: 5354
    protocol: TCP
    name: mdns-tcp
  - port: 5354
    targetPort: 5354
    protocol: UDP
    name: mdns-udp
  selector:
    openstack-app: designate-mdns
