apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-db
  name: designate-db
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3315
    protocol: TCP
    targetPort: 3315
  selector:
    openstack-app: designate-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate
  name: designate
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    openstack-app: designate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: designate-dns
  name: designate-dns
  namespace: os-designate
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 553
    protocol: TCP
    targetPort: 553
    name: dns-tcp
  - port: 553
    protocol: UDP
    targetPort: 553
    name: dns-udp
  selector:
    openstack-app: designate-dns
