apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: commissaire-etcd
  name: commissaire-etcd
  namespace: os-commissaire
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
    name: etcd
  - port: 2380
    targetPort: 2380
    protocol: TCP
    name: etcd-peers
  selector:
    openstack-app: commissaire-etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: commissaire
  name: commissaire
  namespace: os-commissaire
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: c-api
  selector:
    openstack-app: commissaire
