#!/bin/bash

# Copyright 2016 Port Direct
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

: ${OS_DOMAIN:="kube.local"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST OS_DOMAIN"


# Node Etcd Settings
: ${NODE_ETCD_SERVICE_NAMESPACE:="os-node"}
: ${NODE_ETCD_SERVICE_HOSTNAME:="node-etcd"}
: ${NODE_ETCD_SERVICE_HOST:="${NODE_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NODE_ETCD_SERVICE_HOST_SVC:="${NODE_ETCD_HOSTNAME}.${NODE_ETCD_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NODE_ETCD_SERVICE_HOSTNAME NODE_ETCD_SERVICE_HOST NODE_ETCD_SERVICE_HOST_SVC"


# Kube Etcd Settings
: ${KUBE_ETCD_SERVICE_NAMESPACE:="kube-system"}
: ${KUBE_ETCD_SERVICE_HOSTNAME:="kube-etcd"}
: ${KUBE_ETCD_SERVICE_HOST:="${KUBE_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KUBE_ETCD_SERVICE_HOST_SVC:="${KUBE_ETCD_HOSTNAME}.${KUBE_ETCD_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KUBE_ETCD_SERVICE_HOSTNAME KUBE_ETCD_SERVICE_HOST KUBE_ETCD_SERVICE_HOST_SVC"


# Docker Etcd Settings
: ${DOCKER_ETCD_SERVICE_NAMESPACE:="os-docker"}
: ${DOCKER_ETCD_SERVICE_HOSTNAME:="docker-etcd"}
: ${DOCKER_ETCD_SERVICE_HOST:="${DOCKER_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${DOCKER_ETCD_SERVICE_HOST_SVC:="${DOCKER_ETCD_HOSTNAME}.${DOCKER_ETCD_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST DOCKER_ETCD_SERVICE_HOSTNAME DOCKER_ETCD_SERVICE_HOST DOCKER_ETCD_SERVICE_HOST_SVC"


# Openstack Etcd Settings
: ${OPENSTACK_ETCD_SERVICE_NAMESPACE:="os-openstack"}
: ${OPENSTACK_ETCD_SERVICE_HOSTNAME:="openstack-etcd"}
: ${OPENSTACK_ETCD_SERVICE_HOST:="${OPENSTACK_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${OPENSTACK_ETCD_SERVICE_HOST_SVC:="${OPENSTACK_ETCD_HOSTNAME}.${OPENSTACK_ETCD_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST OPENSTACK_ETCD_SERVICE_HOSTNAME OPENSTACK_ETCD_SERVICE_HOST OPENSTACK_ETCD_SERVICE_HOST_SVC"


# Kube Settings
: ${KUBERNETES_SERVICE_NAMESPACE:="default"}
: ${KUBERNETES_HOSTNAME:="kubernetes"}
: ${KUBERNETES_SERVICE_HOST:="${KUBERNETES_HOSTNAME}.$OS_DOMAIN"}
: ${KUBERNETES_SERVICE_HOST_SVC:="${KUBERNETES_HOSTNAME}.${KUBERNETES_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KUBERNETES_HOSTNAME KUBERNETES_SERVICE_HOST KUBERNETES_SERVICE_HOST_SVC"


# Freeipa Settings
: ${FREEIPA_SERVICE_NAMESPACE:="os-freeipa"}
: ${FREEIPA_HOSTNAME:="freeipa"}
: ${FREEIPA_SERVICE_HOST:="${FREEIPA_HOSTNAME}.$OS_DOMAIN"}
: ${FREEIPA_SERVICE_HOST_SVC:="${FREEIPA_HOSTNAME}.${FREEIPA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST FREEIPA_HOSTNAME FREEIPA_SERVICE_HOST FREEIPA_SERVICE_HOST_SVC"


# Ipsilon Settings
: ${IPSILON_SERVICE_NAMESPACE:="os-ipsilon"}
: ${IPSILON_HOSTNAME:="ipsilon"}
: ${IPSILON_SERVICE_HOST:="${IPSILON_HOSTNAME}.$OS_DOMAIN"}
: ${IPSILON_SERVICE_HOST_SVC:="${IPSILON_HOSTNAME}.${IPSILON_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST IPSILON_HOSTNAME IPSILON_SERVICE_HOST IPSILON_SERVICE_HOST_SVC"


# Portal Settings
: ${PORTAL_SERVICE_NAMESPACE:="os-portal"}
: ${PORTAL_HOSTNAME:="portal"}
: ${PORTAL_SERVICE_HOST:="${PORTAL_HOSTNAME}.$OS_DOMAIN"}
: ${PORTAL_SERVICE_HOST_SVC:="${PORTAL_HOSTNAME}.${PORTAL_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST PORTAL_HOSTNAME PORTAL_SERVICE_HOST PORTAL_SERVICE_HOST_SVC"


# Mariadb Settings
: ${MARIADB_SERVICE_NAMESPACE:="os-database"}
: ${MARIADB_HOSTNAME:="database"}
: ${MARIADB_SERVICE_HOST:="${MARIADB_HOSTNAME}.$OS_DOMAIN"}
: ${MARIADB_SERVICE_HOST_SVC:="${MARIADB_HOSTNAME}.${MARIADB_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MARIADB_SERVICE_HOST MARIADB_HOSTNAME MARIADB_SERVICE_HOST_SVC"


# Mongodb Settings
: ${MONGODB_SERVICE_NAMESPACE:="os-database"}
: ${MONGODB_HOSTNAME:="mongodb"}
: ${MONGODB_SERVICE_HOST:="${MONGODB_HOSTNAME}.$OS_DOMAIN"}
: ${MONGODB_SERVICE_HOST_SVC:="${MONGODB_HOSTNAME}.${MONGODB_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MONGODB_SERVICE_HOST MONGODB_HOSTNAME MONGODB_SERVICE_HOST_SVC"


# Messaging Settings
: ${RABBITMQ_SERVICE_NAMESPACE:="os-messaging"}
: ${RABBITMQ_HOSTNAME:="messaging"}
: ${RABBITMQ_SERVICE_HOST:="${RABBITMQ_HOSTNAME}.$OS_DOMAIN"}
: ${RABBITMQ_SERVICE_HOST_SVC:="${RABBITMQ_HOSTNAME}.${RABBITMQ_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST RABBITMQ_HOSTNAME RABBITMQ_SERVICE_HOST RABBITMQ_SERVICE_HOST_SVC"


# Memcached Settings
: ${MEMCACHE_SERVICE_NAMESPACE:="os-memcached"}
: ${MEMCACHE_HOSTNAME:="memcached"}
: ${MEMCACHE_SERVICE_HOST:="${MEMCACHE_HOSTNAME}.$OS_DOMAIN"}
: ${MEMCACHE_SERVICE_HOST_SVC:="${MEMCACHE_HOSTNAME}.${MEMCACHE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MEMCACHE_SERVICE_HOST MEMCACHE_HOSTNAME MEMCACHE_SERVICE_HOST_SVC"


# Keystone Settings
: ${KEYSTONE_SERVICE_NAMESPACE:="os-keystone"}
: ${KEYSTONE_API_SERVICE_HOSTNAME:="keystone"}
: ${KEYSTONE_API_SERVICE_HOST:="${KEYSTONE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KEYSTONE_API_SERVICE_HOST_SVC:="${KEYSTONE_API_SERVICE_HOSTNAME}.${KEYSTONE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KEYSTONE_API_SERVICE_HOSTNAME KEYSTONE_API_SERVICE_HOST KEYSTONE_API_SERVICE_HOST_SVC"


# OVN Settings
: ${OVN_SERVICE_NAMESPACE:="os-ovn"}
: ${OVN_SB_DB_SERVICE_HOSTNAME:="ovn"}
: ${OVN_SB_DB_SERVICE_HOST:="${OVN_SB_DB_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${OVN_SB_DB_SERVICE_HOST_SVC:="${OVN_SB_DB_SERVICE_HOSTNAME}.${OVN_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${OVN_NB_DB_SERVICE_HOSTNAME:="ovn-northbound-db"}
: ${OVN_NB_DB_SERVICE_HOST:="${OVN_NB_DB_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${OVN_NB_DB_SERVICE_HOST_SVC:="${OVN_NB_DB_SERVICE_HOSTNAME}.${OVN_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST OVN_SB_DB_SERVICE_HOSTNAME OVN_SB_DB_SERVICE_HOST OVN_SB_DB_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST OVN_NB_DB_SERVICE_HOSTNAME OVN_NB_DB_SERVICE_HOST OVN_NB_DB_SERVICE_HOST_SVC"


# Neutron Settings
: ${NEUTRON_SERVICE_NAMESPACE:="os-neutron"}
: ${NEUTRON_API_SERVICE_HOSTNAME:="neutron"}
: ${NEUTRON_API_SERVICE_HOST:="${NEUTRON_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NEUTRON_API_SERVICE_HOST_SVC:="${NEUTRON_API_SERVICE_HOSTNAME}.${NEUTRON_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NEUTRON_API_SERVICE_HOSTNAME NEUTRON_API_SERVICE_HOST NEUTRON_API_SERVICE_HOST_SVC"


# Horizon Settings
: ${HORIZON_SERVICE_NAMESPACE:="os-api"}
: ${HORIZON_API_SERVICE_HOSTNAME:="api"}
: ${HORIZON_API_SERVICE_HOST:="${HORIZON_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${HORIZON_API_SERVICE_HOST_SVC:="${HORIZON_API_SERVICE_HOSTNAME}.${HORIZON_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HORIZON_API_SERVICE_HOSTNAME HORIZON_API_SERVICE_HOST HORIZON_API_SERVICE_HOST_SVC"


# loadbalancer Settings
: ${LOADBALANCER_SERVICE_NAMESPACE:="os-loadbalancer"}
: ${LOADBALANCER_API_SERVICE_HOSTNAME:="loadbalancer"}
: ${LOADBALANCER_API_SERVICE_HOST:="${LOADBALANCER_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${LOADBALANCER_API_SERVICE_HOST_SVC:="${LOADBALANCER_API_SERVICE_HOSTNAME}.${LOADBALANCER_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST LOADBALANCER_API_SERVICE_HOSTNAME LOADBALANCER_API_SERVICE_HOST LOADBALANCER_API_SERVICE_HOST_SVC"


# Glance Settings
: ${GLANCE_SERVICE_NAMESPACE:="os-glance"}
: ${GLANCE_API_SERVICE_HOSTNAME:="glance"}
: ${GLANCE_API_SERVICE_HOST:="${GLANCE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${GLANCE_API_SERVICE_HOST_SVC:="${GLANCE_API_SERVICE_HOSTNAME}.${GLANCE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${GLANCE_REGISTRY_SERVICE_HOSTNAME:="glance-registry"}
: ${GLANCE_REGISTRY_SERVICE_HOST:="${GLANCE_REGISTRY_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${GLANCE_REGISTRY_SERVICE_HOST_SVC:="${GLANCE_REGISTRY_SERVICE_HOSTNAME}.${GLANCE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GLANCE_API_SERVICE_HOSTNAME GLANCE_API_SERVICE_HOST GLANCE_API_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GLANCE_REGISTRY_SERVICE_HOSTNAME GLANCE_REGISTRY_SERVICE_HOST GLANCE_REGISTRY_SERVICE_HOST_SVC"


# Cinder Settings
: ${CINDER_SERVICE_NAMESPACE:="os-cinder"}
: ${CINDER_API_SERVICE_HOSTNAME:="cinder"}
: ${CINDER_API_SERVICE_HOST:="${CINDER_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${CINDER_API_SERVICE_HOST_SVC:="${CINDER_API_SERVICE_HOSTNAME}.${CINDER_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST CINDER_API_SERVICE_HOSTNAME CINDER_API_SERVICE_HOST CINDER_API_SERVICE_HOST_SVC"


# Nova Settings
: ${NOVA_SERVICE_NAMESPACE:="os-nova"}
: ${NOVA_API_SERVICE_HOSTNAME:="nova"}
: ${NOVA_API_SERVICE_HOST:="${NOVA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NOVA_API_SERVICE_HOST_SVC:="${NOVA_API_SERVICE_HOSTNAME}.${NOVA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${NOVA_METADATA_SERVICE_HOSTNAME:="metadata"}
: ${NOVA_METADATA_SERVICE_HOST:="${NOVA_METADATA_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NOVA_METADATA_SERVICE_HOST_SVC:="${NOVA_METADATA_SERVICE_HOSTNAME}.${NOVA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${NOVA_SERIAL_SERVICE_HOSTNAME:="serial"}
: ${NOVA_SERIAL_SERVICE_HOST:="${NOVA_SERIAL_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NOVA_SERIAL_SERVICE_HOST_SVC:="${NOVA_SERIAL_SERVICE_HOSTNAME}.${NOVA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${NOVA_SPICE_SERVICE_HOSTNAME:="spice"}
: ${NOVA_SPICE_SERVICE_HOST:="${NOVA_SPICE_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NOVA_SPICE_SERVICE_HOST_SVC:="${NOVA_SPICE_SERVICE_HOSTNAME}.${NOVA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${NOVA_VNC_SERVICE_HOSTNAME:="vnc"}
: ${NOVA_VNC_SERVICE_HOST:="${NOVA_VNC_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${NOVA_VNC_SERVICE_HOST_SVC:="${NOVA_VNC_SERVICE_HOSTNAME}.${NOVA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_API_SERVICE_HOSTNAME NOVA_API_SERVICE_HOST NOVA_API_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_METADATA_SERVICE_HOSTNAME NOVA_METADATA_SERVICE_HOST NOVA_METADATA_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_SERIAL_SERVICE_HOSTNAME NOVA_SERIAL_SERVICE_HOST NOVA_SERIAL_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_SPICE_SERVICE_HOSTNAME NOVA_SPICE_SERVICE_HOST NOVA_SPICE_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_VNC_SERVICE_HOSTNAME NOVA_VNC_SERVICE_HOST NOVA_VNC_SERVICE_HOST_SVC"


# Heat Settings
: ${HEAT_SERVICE_NAMESPACE:="os-heat"}
: ${HEAT_API_SERVICE_HOSTNAME:="heat"}
: ${HEAT_API_SERVICE_HOST:="${HEAT_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${HEAT_API_SERVICE_HOST_SVC:="${HEAT_API_SERVICE_HOSTNAME}.${HEAT_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_SERVICE_HOSTNAME HEAT_API_SERVICE_HOST HEAT_API_SERVICE_HOST_SVC"


# Heat CFN Settings
: ${HEAT_API_CFN_SERVICE_HOSTNAME:="heat-cfn"}
: ${HEAT_API_CFN_SERVICE_HOST:="${HEAT_API_CFN_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${HEAT_API_CFN_SERVICE_HOST_SVC:="${HEAT_API_CFN_SERVICE_HOSTNAME}.${HEAT_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_CFN_SERVICE_HOSTNAME HEAT_API_CFN_SERVICE_HOST HEAT_API_CFN_SERVICE_HOST_SVC"


# Heat CloudWatch Settings
: ${HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME:="heat-cloudwatch"}
: ${HEAT_API_CLOUDWATCH_SERVICE_HOST:="${HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${HEAT_API_CLOUDWATCH_SERVICE_HOST_SVC:="${HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME}.${HEAT_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME HEAT_API_CLOUDWATCH_SERVICE_HOST HEAT_API_CLOUDWATCH_SERVICE_HOST_SVC"


# Murano Settings
: ${MURANO_SERVICE_NAMESPACE:="os-murano"}
: ${MURANO_API_SERVICE_HOSTNAME:="murano"}
: ${MURANO_API_SERVICE_HOST:="${MURANO_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${MURANO_API_SERVICE_HOST_SVC:="${MURANO_API_SERVICE_HOSTNAME}.${MURANO_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
: ${MURANO_MESSAGING_SERVICE_HOSTNAME:="murano-ampq"}
: ${MURANO_MESSAGING_SERVICE_HOST:="${MURANO_MESSAGING_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${MURANO_MESSAGING_SERVICE_HOST_SVC:="${MURANO_MESSAGING_SERVICE_HOSTNAME}.${MURANO_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MURANO_API_SERVICE_HOSTNAME MURANO_API_SERVICE_HOST MURANO_API_SERVICE_HOST_SVC"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MURANO_MESSAGING_SERVICE_HOSTNAME MURANO_MESSAGING_SERVICE_HOST MURANO_MESSAGING_SERVICE_HOST_SVC"


# Swift Settings
: ${SWIFT_SERVICE_NAMESPACE:="os-swift"}
: ${SWIFT_API_SERVICE_HOSTNAME:="swift"}
: ${SWIFT_API_SERVICE_HOST:="${SWIFT_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${SWIFT_API_SERVICE_HOST_SVC:="${NEUTRON_API_SERVICE_HOSTNAME}.${NEUTRON_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST SWIFT_API_SERVICE_HOSTNAME SWIFT_API_SERVICE_HOST SWIFT_API_SERVICE_HOST_SVC"



# Sahara Settings
: ${SAHARA_SERVICE_NAMESPACE:="os-sahara"}
: ${SAHARA_API_SERVICE_HOSTNAME:="sahara"}
: ${SAHARA_API_SERVICE_HOST:="${SAHARA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${SAHARA_API_SERVICE_HOST_SVC:="${SAHARA_API_SERVICE_HOSTNAME}.${SAHARA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST SAHARA_API_SERVICE_HOSTNAME SAHARA_API_SERVICE_HOST SAHARA_API_SERVICE_HOST_SVC"


# Ceilometer Settings
: ${CEILOMETER_SERVICE_NAMESPACE:="os-ceilometer"}
: ${CEILOMETER_API_SERVICE_HOSTNAME:="ceilometer"}
: ${CEILOMETER_API_SERVICE_HOST:="${CEILOMETER_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${CEILOMETER_API_SERVICE_HOST_SVC:="${CEILOMETER_API_SERVICE_HOSTNAME}.${CEILOMETER_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST CEILOMETER_API_SERVICE_HOSTNAME CEILOMETER_API_SERVICE_HOST CEILOMETER_API_SERVICE_HOST_SVC"


# Gnocchi Settings
: ${GNOCCHI_SERVICE_NAMESPACE:="os-gnocchi"}
: ${GNOCCHI_API_SERVICE_HOSTNAME:="gnocchi"}
: ${GNOCCHI_API_SERVICE_HOST:="${GNOCCHI_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${GNOCCHI_API_SERVICE_HOST_SVC:="${GNOCCHI_API_SERVICE_HOSTNAME}.${GNOCCHI_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GNOCCHI_API_SERVICE_HOSTNAME GNOCCHI_API_SERVICE_HOST GNOCCHI_API_SERVICE_HOST_SVC"


# Magnum Settings
: ${MAGNUM_SERVICE_NAMESPACE:="os-magnum"}
: ${MAGNUM_API_SERVICE_HOSTNAME:="magnum"}
: ${MAGNUM_API_SERVICE_HOST:="${MAGNUM_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${MAGNUM_API_SERVICE_HOST_SVC:="${MAGNUM_API_SERVICE_HOSTNAME}.${MAGNUM_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MAGNUM_API_SERVICE_HOSTNAME MAGNUM_API_SERVICE_HOST MAGNUM_API_SERVICE_HOST_SVC"


# Barbican Settings
: ${BARBICAN_SERVICE_NAMESPACE:="os-barbican"}
: ${BARBICAN_API_SERVICE_HOSTNAME:="barbican"}
: ${BARBICAN_API_SERVICE_HOST:="${BARBICAN_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${BARBICAN_API_SERVICE_HOST_SVC:="${BARBICAN_API_SERVICE_HOSTNAME}.${BARBICAN_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST BARBICAN_API_SERVICE_HOSTNAME BARBICAN_API_SERVICE_HOST BARBICAN_API_SERVICE_HOST_SVC"


# Trove Settings
: ${TROVE_SERVICE_NAMESPACE:="os-trove"}
: ${TROVE_API_SERVICE_HOSTNAME:="trove"}
: ${TROVE_API_SERVICE_HOST:="${TROVE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${TROVE_API_SERVICE_HOST_SVC:="${TROVE_API_SERVICE_HOSTNAME}.${TROVE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST TROVE_API_SERVICE_HOSTNAME TROVE_API_SERVICE_HOST TROVE_API_SERVICE_HOST_SVC"


# Manila Settings
: ${MANILA_SERVICE_NAMESPACE:="os-manila"}
: ${MANILA_API_SERVICE_HOSTNAME:="manila"}
: ${MANILA_API_SERVICE_HOST:="${MANILA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${MANILA_API_SERVICE_HOST_SVC:="${MANILA_API_SERVICE_HOSTNAME}.${MANILA_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MANILA_API_SERVICE_HOSTNAME MANILA_API_SERVICE_HOSTNAME MANILA_API_SERVICE_HOST_SVC"


# Designate Settings
: ${DESIGNATE_SERVICE_NAMESPACE:="os-designate"}
: ${DESIGNATE_API_SERVICE_HOSTNAME:="designate"}
: ${DESIGNATE_API_SERVICE_HOST:="${DESIGNATE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${DESIGNATE_API_SERVICE_HOST_SVC:="${DESIGNATE_API_SERVICE_HOSTNAME}.${DESIGNATE_SERVICE_NAMESPACE}.svc.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST DESIGNATE_API_SERVICE_HOSTNAME DESIGNATE_API_SERVICE_HOST DESIGNATE_API_SERVICE_HOST_SVC"
