#!/bin/sh
: ${OS_DOMAIN:="kube.local"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST OS_DOMAIN"

# ECTD Settings
: ${ETCDCTL_ENDPOINT:="http://etcd.os-etcd.svc.${OS_DOMAIN}:4001"}
: ${NODE_ETCD_SERVICE_HOSTNAME:="node-etcd"}
: ${NODE_ETCD_SERVICE_HOST:="${NODE_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KUBE_ETCD_SERVICE_HOSTNAME:="kube-etcd"}
: ${KUBE_ETCD_SERVICE_HOST:="${KUBE_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${DOCKER_ETCD_SERVICE_HOSTNAME:="docker-etcd"}
: ${DOCKER_ETCD_SERVICE_HOST:="${DOCKER_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${OPENSTACK_ETCD_SERVICE_HOSTNAME:="openstack-etcd"}
: ${OPENSTACK_ETCD_SERVICE_HOST:="${OPENSTACK_ETCD_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST ETCDCTL_ENDPOINT \
NODE_ETCD_SERVICE_HOSTNAME NODE_ETCD_SERVICE_HOST \
KUBE_ETCD_SERVICE_HOSTNAME KUBE_ETCD_SERVICE_HOST \
DOCKER_ETCD_SERVICE_HOSTNAME DOCKER_ETCD_SERVICE_HOST \
OPENSTACK_ETCD_SERVICE_HOSTNAME OPENSTACK_ETCD_SERVICE_HOST"


# Kube Settings
: ${KUBERNETES_HOSTNAME:="kubernetes"}
: ${KUBERNETES_SERVICE_HOST:="${KUBERNETES_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KUBERNETES_HOSTNAME KUBERNETES_SERVICE_HOST"

# Freeipa Settings
: ${FREEIPA_HOSTNAME:="freeipa"}
: ${FREEIPA_SERVICE_HOST:="${FREEIPA_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST FREEIPA_HOSTNAME FREEIPA_SERVICE_HOST"

# Ipsilon Settings
: ${IPSILON_HOSTNAME:="ipsilon"}
: ${IPSILON_SERVICE_HOST:="${IPSILON_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST IPSILON_HOSTNAME IPSILON_SERVICE_HOST"

# DB Settings
: ${MARIADB_HOSTNAME:="database"}
: ${MARIADB_SERVICE_HOST:="${MARIADB_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MARIADB_SERVICE_HOST MARIADB_HOSTNAME"
: ${MONGODB_HOSTNAME:="mongodb"}
: ${MONGODB_SERVICE_HOST:="${MONGODB_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MONGODB_SERVICE_HOST MONGODB_HOSTNAME"


# Messaging Settings
: ${RABBITMQ_HOSTNAME:="messaging"}
: ${RABBITMQ_SERVICE_HOST:="${RABBITMQ_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST RABBITMQ_HOSTNAME RABBITMQ_SERVICE_HOST"


# Keystone Settings
: ${KEYSTONE_ADMIN_SERVICE_HOSTNAME:="keystone"}
: ${KEYSTONE_ADMIN_SERVICE_HOST:="${KEYSTONE_ADMIN_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KEYSTONE_PUBLIC_SERVICE_HOSTNAME:="keystone"}
: ${KEYSTONE_PUBLIC_SERVICE_HOST:="${KEYSTONE_PUBLIC_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KEYSTONE_OLD_ADMIN_SERVICE_HOSTNAME:="keystone-v2"}
: ${KEYSTONE_OLD_ADMIN_SERVICE_HOST:="${KEYSTONE_OLD_ADMIN_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${KEYSTONE_OLD_PUBLIC_SERVICE_HOSTNAME:="keystone-v2"}
: ${KEYSTONE_OLD_PUBLIC_SERVICE_HOST:="${KEYSTONE_OLD_PUBLIC_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KEYSTONE_ADMIN_SERVICE_HOSTNAME KEYSTONE_ADMIN_SERVICE_HOST"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KEYSTONE_PUBLIC_SERVICE_HOSTNAME KEYSTONE_PUBLIC_SERVICE_HOST"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KEYSTONE_OLD_ADMIN_SERVICE_HOSTNAME KEYSTONE_OLD_ADMIN_SERVICE_HOST"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST KEYSTONE_OLD_PUBLIC_SERVICE_HOSTNAME KEYSTONE_OLD_PUBLIC_SERVICE_HOST"

# Glance Settings
: ${GLANCE_API_SERVICE_HOSTNAME:="glance"}
: ${GLANCE_API_SERVICE_HOST:="${GLANCE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
: ${GLANCE_REGISTRY_SERVICE_HOSTNAME:="glance-registry"}
: ${GLANCE_REGISTRY_SERVICE_HOST:="${GLANCE_REGISTRY_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GLANCE_API_SERVICE_HOSTNAME GLANCE_API_SERVICE_HOST"
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GLANCE_REGISTRY_SERVICE_HOSTNAME GLANCE_REGISTRY_SERVICE_HOST"

# Nova Settings
: ${NOVA_API_SERVICE_HOSTNAME:="nova"}
: ${NOVA_API_SERVICE_HOST:="${NOVA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NOVA_API_SERVICE_HOSTNAME NOVA_API_SERVICE_HOST"

# Neutron Settings
: ${NEUTRON_API_SERVICE_HOSTNAME:="neutron"}
: ${NEUTRON_API_SERVICE_HOST:="${NEUTRON_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST NEUTRON_API_SERVICE_HOSTNAME NEUTRON_API_SERVICE_HOST"

# Swift Settings
: ${SWIFT_API_SERVICE_HOSTNAME:="swift"}
: ${SWIFT_API_SERVICE_HOST:="${SWIFT_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST SWIFT_API_SERVICE_HOSTNAME SWIFT_API_SERVICE_HOST"

# Cinder Settings
: ${CINDER_API_SERVICE_HOSTNAME:="cinder"}
: ${CINDER_API_SERVICE_HOST:="${CINDER_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST CINDER_API_SERVICE_HOSTNAME CINDER_API_SERVICE_HOST"

# Heat Settings
: ${HEAT_API_SERVICE_HOSTNAME:="heat"}
: ${HEAT_API_SERVICE_HOST:="${HEAT_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_SERVICE_HOSTNAME HEAT_API_SERVICE_HOST"

# Heat CFN Settings
: ${HEAT_API_CFN_SERVICE_HOSTNAME:="heat-cfn"}
: ${HEAT_API_CFN_SERVICE_HOST:="${HEAT_API_CFN_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_CFN_SERVICE_HOSTNAME HEAT_API_CFN_SERVICE_HOST"

# Heat CloudWatch Settings
: ${HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME:="heat-cloudwatch"}
: ${HEAT_API_CLOUDWATCH_SERVICE_HOST:="${HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST HEAT_API_CLOUDWATCH_SERVICE_HOSTNAME HEAT_API_CLOUDWATCH_SERVICE_HOST"

# Murano Settings
: ${MURANO_API_SERVICE_HOSTNAME:="murano"}
: ${MURANO_API_SERVICE_HOST:="${MURANO_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MURANO_API_SERVICE_HOSTNAME MURANO_API_SERVICE_HOST"

# Sahara Settings
: ${SAHARA_API_SERVICE_HOSTNAME:="sahara"}
: ${SAHARA_API_SERVICE_HOST:="${SAHARA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST SAHARA_API_SERVICE_HOSTNAME SAHARA_API_SERVICE_HOST"

# Ceilometer Settings
: ${CEILOMETER_API_SERVICE_HOSTNAME:="ceilometer"}
: ${CEILOMETER_API_SERVICE_HOST:="${CEILOMETER_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST CEILOMETER_API_SERVICE_HOSTNAME CEILOMETER_API_SERVICE_HOST"

# Gnocchi Settings
: ${GNOCCHI_API_SERVICE_HOSTNAME:="gnocchi"}
: ${GNOCCHI_API_SERVICE_HOST:="${GNOCCHI_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST GNOCCHI_API_SERVICE_HOSTNAME GNOCCHI_API_SERVICE_HOST"

# Magnum Settings
: ${MAGNUM_API_SERVICE_HOSTNAME:="magnum"}
: ${MAGNUM_API_SERVICE_HOST:="${MAGNUM_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MAGNUM_API_SERVICE_HOSTNAME MAGNUM_API_SERVICE_HOST"

# Barbican Settings
: ${BARBICAN_API_SERVICE_HOSTNAME:="barbican"}
: ${BARBICAN_API_SERVICE_HOST:="${BARBICAN_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST BARBICAN_API_SERVICE_HOSTNAME BARBICAN_API_SERVICE_HOST"

# Trove Settings
: ${TROVE_API_SERVICE_HOSTNAME:="trove"}
: ${TROVE_API_SERVICE_HOST:="${TROVE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST TROVE_API_SERVICE_HOSTNAME TROVE_API_SERVICE_HOST"

# Manila Settings
: ${MANILA_API_SERVICE_HOSTNAME:="manila"}
: ${MANILA_API_SERVICE_HOST:="${MANILA_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST MANILA_API_SERVICE_HOSTNAME MANILA_API_SERVICE_HOSTNAME"

# Designate Settings
: ${DESIGNATE_API_SERVICE_HOSTNAME:="designate"}
: ${DESIGNATE_API_SERVICE_HOST:="${DESIGNATE_API_SERVICE_HOSTNAME}.$OS_DOMAIN"}
SERVICE_HOSTS_ENV_LIST="$SERVICE_HOSTS_ENV_LIST DESIGNATE_API_SERVICE_HOSTNAME DESIGNATE_API_SERVICE_HOST"
