#!/usr/bin/expect
set timeout 20
set arg1 [lindex $argv 0]
set arg2 [lindex $argv 1]
set arg3 [lindex $argv 2]
spawn kinit $arg1
expect "Password for" { send "$arg2\r" }
expect "Enter new password:" { send "$arg3\r" }
expect "Enter it again:" { send "$arg3\r" }
interact
