# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# gnocchi-ssl-secret - from marina service manager
# gnocchi-user-ssl-secret - from marina service manager
# gnocchi-db-ssl-secret - from marina service manager
# gnocchi-etcd-ssl-secret - from marina service manager
# grafana-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-kubecfg
  namespace: os-gnocchi
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-user-ipa
  namespace: os-gnocchi
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-host-ipa
  namespace: os-gnocchi
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-db-root
  namespace: os-gnocchi
type: Opaque
data:
  mariadb-root-password: {{ AUTH_GNOCCHI_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-db
  namespace: os-gnocchi
type: Opaque
data:
  mariadb-test-database: {{ AUTH_GNOCCHI_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_GNOCCHI_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_GNOCCHI_MARIADB_PASSWORD }}
  gnocchi-db-name: {{ AUTH_GNOCCHI_DB_NAME }}
  gnocchi-db-user: {{ AUTH_GNOCCHI_DB_USER }}
  gnocchi-db-password: {{ AUTH_GNOCCHI_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-db-grafana-root
  namespace: os-gnocchi
type: Opaque
data:
  grafana-db-root-name: {{ AUTH_GNOCCHI_GRAFANA_DB_ROOT_NAME }}
  grafana-db-root-user: {{ AUTH_GNOCCHI_GRAFANA_DB_ROOT_USER }}
  grafana-db-root-password: {{ AUTH_GNOCCHI_GRAFANA_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-db-grafana
  namespace: os-gnocchi
type: Opaque
data:
  grafana-db-name: {{ AUTH_GNOCCHI_GRAFANA_DB_NAME }}
  grafana-db-user: {{ AUTH_GNOCCHI_GRAFANA_DB_USER }}
  grafana-db-password: {{ AUTH_GNOCCHI_GRAFANA_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-keystone
  namespace: os-gnocchi
type: Opaque
data:
  gnocchi-keystone-user: {{ AUTH_GNOCCHI_KEYSTONE_USER }}
  gnocchi-keystone-password: {{ AUTH_GNOCCHI_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-ldap
  namespace: os-gnocchi
type: Opaque
data:
  gnocchi-grafana-ldap-user: {{ AUTH_GNOCCHI_GRAFANA_LDAP_USER }}
  gnocchi-grafana-ldap-password: {{ AUTH_GNOCCHI_GRAFANA_LDAP_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-statsd
  namespace: os-gnocchi
type: Opaque
data:
  gnocchi-statsd-resource-id: {{ AUTH_GNOCCHI_STATSD_RESOURCE_ID }}
  gnocchi-statsd-project-id: {{ AUTH_GNOCCHI_STATSD_PROJECT_ID }}
  gnocchi-statsd-user-id: {{ AUTH_GNOCCHI_STATSD_USER_ID }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-grafana-secret-key
  namespace: os-gnocchi
type: Opaque
data:
  gnocchi-grafana-secret-key: {{ AUTH_GNOCCHI_GRAFANA_SECRET_KEY }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-email
  namespace: os-portal
type: Opaque
data:
  smtp-host: {{ AUTH_GNOCCHI_GRAFANA_SMTP_HOST }}
  smtp-port: {{ AUTH_GNOCCHI_GRAFANA_SMTP_PORT }}
  smtp-user: {{ AUTH_GNOCCHI_GRAFANA_SMTP_USER }}
  smtp-pass: {{ AUTH_GNOCCHI_GRAFANA_SMTP_PASS }}
  email-addr-from: {{ AUTH_GNOCCHI_GRAFANA_DEFAULT_FROM_EMAIL }}
  email-addr-admin: {{ AUTH_GNOCCHI_GRAFANA_DEFAULT_ADMIN_EMAIL }}
