apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: gnocchi-db
  name: gnocchi-db
  namespace: os-gnocchi
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3320
    protocol: TCP
    targetPort: 3320
  selector:
    openstack-app: gnocchi-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: gnocchi-etcd
  name: gnocchi-etcd
  namespace: os-gnocchi
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
    name: etcd
  - port: 7002
    protocol: TCP
    targetPort: 7002
    name: etcd-peers
  selector:
    openstack-app: gnocchi-etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: gnocchi
  name: gnocchi
  namespace: os-gnocchi
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8041
    protocol: TCP
    targetPort: 8041
  selector:
    openstack-app: gnocchi
