# Additional secrets required by this namespace:
# barbican-kra-agent-secret - from marina freeipa
# messaging-auth - from os-messaging namepace defs
# barbican-ssl-secret - from marina service manager
# barbican-user-ssl-secret - from marina service manager
# barbican-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: barbican-kubecfg
  namespace: os-barbican
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-user-ipa
  namespace: os-barbican
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-host-ipa
  namespace: os-barbican
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-db-root
  namespace: os-barbican
type: Opaque
data:
  mariadb-root-password: {{ AUTH_BARBICAN_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-db
  namespace: os-barbican
type: Opaque
data:
  mariadb-test-database: {{ AUTH_BARBICAN_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_BARBICAN_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_BARBICAN_MARIADB_PASSWORD }}
  barbican-db-name: {{ AUTH_BARBICAN_DB_NAME }}
  barbican-db-user: {{ AUTH_BARBICAN_DB_USER }}
  barbican-db-password: {{ AUTH_BARBICAN_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-keystone
  namespace: os-barbican
type: Opaque
data:
  barbican-keystone-user: {{ AUTH_BARBICAN_KEYSTONE_USER }}
  barbican-keystone-password: {{ AUTH_BARBICAN_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: barbican-keystone-service
  namespace: os-barbican
type: Opaque
data:
  barbican-keystone-service-user: {{ AUTH_BARBICAN_KEYSTONE_SERVICE_USER }}
  barbican-keystone-service-password: {{ AUTH_BARBICAN_KEYSTONE_SERVICE_PASSWORD }}
