apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    openstack-app: commissaire
    version: v0.1.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/rewrite-target: /
  name: commissaire
  namespace: os-commissaire
spec:
  tls:
    - hosts:
        - commissaire.{{ OS_DOMAIN }}
      secretName: commissaire-ssl-secret
    - hosts:
        - commissaire.os-commissaire.svc.{{ OS_DOMAIN }}
      secretName: commissaire-ssl-secret
  rules:
  - host: commissaire.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: commissaire
          servicePort: 8001
  - host: commissaire.os-commissaire.svc.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: commissaire
          servicePort: 8001
