apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    openstack-app: designate
    version: v0.1.0
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/rewrite-target: /
  name: designate
  namespace: os-designate
spec:
  tls:
    - hosts:
        - designate.{{ OS_DOMAIN }}
      secretName: designate-ssl-secret
    - hosts:
        - designate.os-designate.svc.{{ OS_DOMAIN }}
      secretName: designate-ssl-secret
  rules:
  - host: designate.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: designate
          servicePort: 9001
  - host: designate.os-designate.svc.{{ OS_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: designate
          servicePort: 9001
