#!/bin/bash

# Copyright 2014--2016 Jan Pazdziora
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e

HOSTNAME=$( uname -n )

function update_server_ip_address () {
  CURRENT_IP=$( dig +short -t A $HOSTNAME )
  MY_IP=''
  if [ -f /run/ipa/ipa-server-ip ] ; then
    MY_IP=$( cat /run/ipa/ipa-server-ip )
  fi
  MY_IP=${MY_IP:-$( /sbin/ip addr show | awk '/inet .*global/ { split($2,a,"/"); print a[1]; }' | head -1 )}
  if [ "$CURRENT_IP" == "$MY_IP" ] ; then
    return
  fi

  kdestroy -A
  kinit -k
  (
    echo "update add $HOSTNAME 180 A $MY_IP"
    echo "update delete $HOSTNAME A $CURRENT_IP"
    echo "send"
    echo "quit"
  ) | nsupdate -g
  kdestroy -A

  while true ; do
    NEW_IP=$( dig +short -t A $HOSTNAME )
    if [ "$NEW_IP" == "$MY_IP" ] ; then
      break
    fi
    sleep 1
  done
}

if systemctl is-active -q named-pkcs11 || [ -f /run/ipa/ipa-server-ip ] ; then
  # Wait until DNS is up and running and resolving
  while ! host -t A $HOSTNAME > /dev/null ; do
    sleep 1
  done
  update_server_ip_address
  host $HOSTNAME
else
  echo "FreeIPA server does not run DNS server, skipping update-self-ip-address."
fi
