cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1

xpack.ssl.key:                     /usr/share/elasticsearch/config/tls.key
xpack.ssl.certificate:             /usr/share/elasticsearch/config/tls.crt
xpack.ssl.certificate_authorities: [ "/usr/share/elasticsearch/config/tls.ca" ]
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true
