#!/bin/bash

# Copyright 2016 Port Direct
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
: ${OS_DISTRO:="HarborOS: Init"}
echo "${OS_DISTRO}: Container starting (FreeIPA Client Container)"
################################################################################
touch /etc/os-environment.env
touch /etc/os-container.env
source /etc/os-environment.env
source /etc/os-container.env

: ${OS_DOMAIN:="$(hostname -d)"}
export OS_DOMAIN
: ${FREEIPA_HOSTNAME:="freeipa"}
: ${FREEIPA_SERVICE_HOST:="${FREEIPA_HOSTNAME}.$OS_DOMAIN"}

source /opt/harbor/harbor-vars.sh
source /opt/harbor/service-hosts.sh
source /opt/harbor/harbor-common.sh


################################################################################
check_required_vars FREEIPA_SERVICE_HOST
touch /etc/resolv.conf
if [ -f ${HARBOR_RESOLV_FILE} ]; then
    echo "${OS_DISTRO}: overriding host resolv.conf"
    cat ${HARBOR_RESOLV_FILE} > /etc/resolv.conf
fi
echo "${OS_DISTRO}: Displaying resolv.conf:"
cat /etc/resolv.conf
boot_checks


################################################################################
TMP_HOSTS="/tmp/$(uuidgen)"
sed "s/$(hostname -s)/$(hostname -s) $(hostname -s).${OS_DOMAIN}/g" /etc/hosts > ${TMP_HOSTS}
cat ${TMP_HOSTS} > /etc/hosts


################################################################################
systemctl daemon-reload
systemctl start systemd-hostnamed.service
systemctl enable systemd-hostnamed.service


if [ -f /etc/ipa/ca.crt ] ; then
  echo "${OS_DISTRO}: IPA: CA Cert found @ /etc/ipa/ca.crt, assuming that we are already enrolled"
  ##############################################################################
else
  echo "${OS_DISTRO}: IPA: Installing client"
  ##############################################################################
  check_required_vars OS_DOMAIN \
                      FREEIPA_SERVICE_HOST \
                      AUTH_FREEIPA_HOST_ADMIN_USER \
                      AUTH_FREEIPA_HOST_ADMIN_PASSWORD

  ipa-client-install \
      --domain=${OS_DOMAIN} \
      --server=${FREEIPA_SERVICE_HOST} \
      --realm=$( echo ${OS_DOMAIN}  | tr '[:lower:]' '[:upper:]' ) \
      --principal=${AUTH_FREEIPA_HOST_ADMIN_USER} \
      --password=${AUTH_FREEIPA_HOST_ADMIN_PASSWORD} \
      --hostname=$(hostname -s).${OS_DOMAIN} \
      --unattended \
      --force \
      --force-join \
      --no-ntp \
      --request-cert \
      --mkhomedir  \
      --ssh-trust-dns \
      --enable-dns-updates
fi

echo "${OS_DISTRO}: Running Container Start script"
################################################################################
exec /start.sh "$@"
