#!/bin/bash
set -e
. /usr/sbin/container-gen-env
: ${OS_DOMAIN:="kube.local"}

source /etc/os-container.env
source /opt/harbor/harbor-vars.sh
. /opt/harbor/service-hosts.sh
. /opt/harbor/harbor-common.sh

boot_checks

if [ -f /init-ipa ]
  then
    ################################################################################
    echo "${OS_DISTRO}: Launching IPA Client enrollment"
    ################################################################################
    exec /init-ipa-client "$@"
  else
    exec /start.sh "$@"
fi
