# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# ceilometer-ssl-secret - from marina service manager
# ceilometer-user-ssl-secret - from marina service manager
# ceilometer-els-ssl-secret - from marina service manager
# ceilometer-etcd-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-kubecfg
  namespace: os-ceilometer
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-user-ipa
  namespace: os-ceilometer
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-host-ipa
  namespace: os-ceilometer
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-db-root
  namespace: os-ceilometer
type: Opaque
data:
  mariadb-root-password: {{ AUTH_CEILOMETER_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-db
  namespace: os-ceilometer
type: Opaque
data:
  mariadb-test-database: {{ AUTH_CEILOMETER_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_CEILOMETER_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_CEILOMETER_MARIADB_PASSWORD }}
  ceilometer-db-name: {{ AUTH_CEILOMETER_DB_NAME }}
  ceilometer-db-user: {{ AUTH_CEILOMETER_DB_USER }}
  ceilometer-db-password: {{ AUTH_CEILOMETER_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-els-root
  namespace: os-ceilometer
type: Opaque
data:
  els-root-password: {{ AUTH_CEILOMETER_ELS_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-els
  namespace: os-ceilometer
type: Opaque
data:
  ceilometer-els-name: {{ AUTH_CEILOMETER_ELS_NAME }}
  ceilometer-els-user: {{ AUTH_CEILOMETER_ELS_USER }}
  ceilometer-els-password: {{ AUTH_CEILOMETER_ELS_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-keystone
  namespace: os-ceilometer
type: Opaque
data:
  ceilometer-keystone-user: {{ AUTH_CEILOMETER_KEYSTONE_USER }}
  ceilometer-keystone-password: {{ AUTH_CEILOMETER_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ceilometer-keystone
  namespace: os-nova
type: Opaque
data:
  ceilometer-keystone-user: {{ AUTH_CEILOMETER_KEYSTONE_USER }}
  ceilometer-keystone-password: {{ AUTH_CEILOMETER_KEYSTONE_PASSWORD }}
