apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ceilometer-els
  name: ceilometer-els
  namespace: os-ceilometer
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
    name: els
  - port: 9300
    protocol: TCP
    targetPort: 9300
    name: els-r
  selector:
    openstack-app: ceilometer-els
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ceilometer-db
  name: ceilometer-db
  namespace: os-ceilometer
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3321
    protocol: TCP
    targetPort: 3321
  selector:
    openstack-app: ceilometer-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ceilometer
  name: ceilometer
  namespace: os-ceilometer
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8777
    protocol: TCP
    targetPort: 8777
  selector:
    openstack-app: ceilometer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: ceilometer-etcd
  name: ceilometer-etcd
  namespace: os-ceilometer
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 4003
    protocol: TCP
    targetPort: 4003
    name: etcd
  - port: 7003
    protocol: TCP
    targetPort: 7003
    name: etcd-peers
  selector:
    openstack-app: ceilometer-etcd
