kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    openstack-app: magnum-db
  name: os-magnum-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/harbor/magnum/mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    openstack-app: magnum-db
  name: os-magnum-db
  namespace: os-magnum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: magnum-manager
    version: v0.1.0
  name: magnum-manager
  namespace: os-magnum
spec:
  template:
    metadata:
      labels:
        openstack-app: magnum-manager
        version: v0.1.0
      name: magnum-manager
      namespace: os-magnum
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: magnum-manager
          image: {{ IMAGE_MAGNUM_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-kubecfg
              mountPath: /var/run/harbor/secrets/config-kubecfg
              readOnly: true
            - name: os-config-user-ipa
              mountPath: /var/run/harbor/secrets/config-user-ipa
              readOnly: true
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-keystone-trustee
              mountPath: /var/run/harbor/secrets/config-keystone-trustee
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
            - name: os-config-keystone-admin-user
              mountPath: /var/run/harbor/secrets/config-keystone-admin-user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: magnum-kubecfg
        - name: os-config-user-ipa
          secret:
            secretName: magnum-user-ipa
        - name: os-config-host-ipa
          secret:
            secretName: magnum-host-ipa
        - name: os-config-db-root
          secret:
            secretName: magnum-db-root
        - name: os-config-db
          secret:
            secretName: magnum-db
        - name: os-config-keystone
          secret:
            secretName: magnum-keystone
        - name: os-config-keystone-trustee
          secret:
            secretName: magnum-keystone-trustee
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-secret
          secret:
            secretName: magnum-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: magnum-user-ssl-secret
        - name: os-config-keystone-admin-user
          secret:
            secretName: keystone-admin-user
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: magnum-db
    version: v0.1.0
  name: magnum-db
  namespace: os-magnum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: magnum-db
        version: v0.1.0
      name: magnum-db
      namespace: os-magnum
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: magnum-db
          image: {{ IMAGE_MARIADB_SERVER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 3318
              hostPort: 3318
              protocol: TCP
              name: mysql
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: DB_PORT
              value: '3318'
            - name: DB_TLS
              value: /run/harbor/auth/db
            - name: DB_ROOT_PASSWORD
              value: AUTH_MAGNUM_DB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: AUTH_MAGNUM_MARIADB_DATABASE
            - name: MARIADB_USER
              value: AUTH_MAGNUM_MARIADB_USER
            - name: MARIADB_PASSWORD
              value: AUTH_MAGNUM_MARIADB_PASSWORD
            - name: DB_NAME
              value: AUTH_MAGNUM_DB_NAME
            - name: DB_USER
              value: AUTH_MAGNUM_DB_USER
            - name: DB_PASSWORD
              value: AUTH_MAGNUM_DB_PASSWORD
          volumeMounts:
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-db-ssl-secret
              mountPath: /run/harbor/auth/db
              readOnly: true
            - mountPath: /var/lib/mysql
              name: os-magnum-db
              readOnly: false
      volumes:
        - name: os-config-db-root
          secret:
            secretName: magnum-db-root
        - name: os-config-db
          secret:
            secretName: magnum-db
        - name: os-config-db-ssl-secret
          secret:
            secretName: magnum-db-ssl-secret
        - name: os-magnum-db
          persistentVolumeClaim:
            claimName: os-magnum-db
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: magnum
    version: v0.1.0
  name: magnum-engine-master
  namespace: os-magnum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: magnum
        version: v0.1.0
      name: magnum-engine-master
      namespace: os-magnum
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[
          {
          	"name": "magnum-engine-init",
          	"image": "{{ IMAGE_MAGNUM_INIT }}",
          	"imagePullPolicy": "{{ IMAGE_PULL_POLICY }}",
          	"env": [
          		{
          			"name": "OS_DOMAIN",
          			"value": "{{ OS_DOMAIN }}"
          		},
          		{
          			"name": "APP_COMPONENT",
          			"value": "engine"
          		},
          		{
          			"name": "APP_USER",
          			"value": "magnum"
          		}
          	],
          	"volumeMounts": [
          		{
          			"name": "os-config-db",
          			"mountPath": "/var/run/harbor/secrets/config-db",
          			"readOnly": true
          		},
          		{
          			"name": "os-config-keystone",
          			"mountPath": "/var/run/harbor/secrets/config-keystone",
          			"readOnly": true
          		},
          		{
          			"name": "os-config-keystone-trustee",
          			"mountPath": "/var/run/harbor/secrets/config-keystone-trustee",
          			"readOnly": true
          		},
          		{
          			"name": "os-config-messaging-auth",
          			"mountPath": "/var/run/harbor/secrets/config-messaging-auth",
          			"readOnly": true
          		},
          		{
          			"name": "os-config-ssl-user-secret",
          			"mountPath": "/run/harbor/auth/user",
          			"readOnly": true
          		},
          		{
          			"name": "pod-etc-magnum",
          			"mountPath": "/pod/etc/magnum",
          			"readOnly": false
          		}
          	],
          	"securityContext": {
          		"privileged": false
          	}
          }
        ]'
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: magnum-engine
          image: {{ IMAGE_MAGNUM_ENGINE }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: pod-etc-magnum
              mountPath: /etc/magnum
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      volumes:
        - name: pod-etc-magnum
          emptyDir: {}
        - name: os-config-db
          secret:
            secretName: magnum-db
        - name: os-config-keystone
          secret:
            secretName: magnum-keystone
        - name: os-config-keystone-trustee
          secret:
            secretName: magnum-keystone-trustee
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-user-secret
          secret:
            secretName: magnum-user-ssl-secret
