# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# magnum-ssl-secret - from marina service manager
# magnum-user-ssl-secret - from marina service manager
# magnum-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: magnum-kubecfg
  namespace: os-magnum
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-user-ipa
  namespace: os-magnum
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-host-ipa
  namespace: os-magnum
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-db-root
  namespace: os-magnum
type: Opaque
data:
  mariadb-root-password: {{ AUTH_MAGNUM_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-db
  namespace: os-magnum
type: Opaque
data:
  mariadb-test-database: {{ AUTH_MAGNUM_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_MAGNUM_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_MAGNUM_MARIADB_PASSWORD }}
  magnum-db-name: {{ AUTH_MAGNUM_DB_NAME }}
  magnum-db-user: {{ AUTH_MAGNUM_DB_USER }}
  magnum-db-password: {{ AUTH_MAGNUM_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-keystone
  namespace: os-magnum
type: Opaque
data:
  magnum-keystone-user: {{ AUTH_MAGNUM_KEYSTONE_USER }}
  magnum-keystone-password: {{ AUTH_MAGNUM_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: magnum-keystone-trustee
  namespace: os-magnum
type: Opaque
data:
  magnum-keystone-trustee-user: {{ AUTH_MAGNUM_KEYSTONE_TRUSTEE_USER }}
  magnum-keystone-trustee-password: {{ AUTH_MAGNUM_KEYSTONE_TRUSTEE_PASSWORD }}
