#!/bin/sh
# Copyright 2014--2016 Jan Pazdziora
# Copyright 2016--2016 Port Direct
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

mark_exit_code () {
  exit_code=$?
  echo $exit_code > /run/ipa/exit_code
  exit $exit_code
}
mkdir -p /run/ipa
trap mark_exit_code ERR EXIT

set -e
################################################################################
echo "${OS_DISTRO}: Running Container Start Script"
################################################################################
. /usr/sbin/container-gen-env


if [ -f /init-ipa ]
  then
    ################################################################################
    echo "${OS_DISTRO}: Launching IPA Client enrollment"
    ################################################################################
    /init-ipa-client
  else
    /init
fi

if true ; then
  echo "Container configured."
  else
    ret=$?
    echo "Container configuration failed." >&2
    exit $ret
  fi
exit
