# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# zun-ssl-secret - from marina service manager
# zun-user-ssl-secret - from marina service manager
# zun-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: zun-kubecfg
  namespace: os-zun
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-user-ipa
  namespace: os-zun
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-host-ipa
  namespace: os-zun
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-db-root
  namespace: os-zun
type: Opaque
data:
  mariadb-root-password: {{ AUTH_ZUN_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-db
  namespace: os-zun
type: Opaque
data:
  mariadb-test-database: {{ AUTH_ZUN_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_ZUN_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_ZUN_MARIADB_PASSWORD }}
  zun-db-name: {{ AUTH_ZUN_DB_NAME }}
  zun-db-user: {{ AUTH_ZUN_DB_USER }}
  zun-db-password: {{ AUTH_ZUN_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-keystone
  namespace: os-zun
type: Opaque
data:
  zun-keystone-user: {{ AUTH_ZUN_KEYSTONE_USER }}
  zun-keystone-password: {{ AUTH_ZUN_KEYSTONE_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zun-keystone-trustee
  namespace: os-zun
type: Opaque
data:
  zun-keystone-trustee-user: {{ AUTH_ZUN_KEYSTONE_TRUSTEE_USER }}
  zun-keystone-trustee-password: {{ AUTH_ZUN_KEYSTONE_TRUSTEE_PASSWORD }}
