# Additional secrets required by this namespace:
# messaging-auth - from os-messaging namepace defs
# mistral-ssl-secret - from marina service manager
# mistral-user-ssl-secret - from marina service manager
# mistral-db-ssl-secret - from marina service manager
apiVersion: v1
kind: Secret
metadata:
  name: mistral-kubecfg
  namespace: os-mistral
type: Opaque
data:
  kube-endpoint: {{ KUBE_ENDPOINT }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mistral-user-ipa
  namespace: os-mistral
type: Opaque
data:
  ipa-user-admin-user: {{ AUTH_FREEIPA_USER_ADMIN_USER }}
  ipa-user-admin-password: {{ AUTH_FREEIPA_USER_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mistral-host-ipa
  namespace: os-mistral
type: Opaque
data:
  ipa-host-admin-user: {{ AUTH_FREEIPA_HOST_ADMIN_USER }}
  ipa-host-admin-password: {{ AUTH_FREEIPA_HOST_ADMIN_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mistral-db-root
  namespace: os-mistral
type: Opaque
data:
  mariadb-root-password: {{ AUTH_MISTRAL_DB_ROOT_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mistral-db
  namespace: os-mistral
type: Opaque
data:
  mariadb-test-database: {{ AUTH_MISTRAL_MARIADB_DATABASE }}
  mariadb-test-user: {{ AUTH_MISTRAL_MARIADB_USER }}
  mariadb-test-password: {{ AUTH_MISTRAL_MARIADB_PASSWORD }}
  mistral-db-name: {{ AUTH_MISTRAL_DB_NAME }}
  mistral-db-user: {{ AUTH_MISTRAL_DB_USER }}
  mistral-db-password: {{ AUTH_MISTRAL_DB_PASSWORD }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mistral-keystone
  namespace: os-mistral
type: Opaque
data:
  mistral-keystone-user: {{ AUTH_MISTRAL_KEYSTONE_USER }}
  mistral-keystone-password: {{ AUTH_MISTRAL_KEYSTONE_PASSWORD }}
