apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: mistral-db
  name: mistral-db
  namespace: os-mistral
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 3319
    protocol: TCP
    targetPort: 3319
  selector:
    openstack-app: mistral-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: mistral
  name: mistral
  namespace: os-mistral
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    openstack-app: mistral
